name: smart_sport_scribe_main
description: Al-Merrikh Flutter app.
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.3.2
  http: ^1.2.2
  video_player: ^2.9.2
  camera: ^0.10.5+9
  google_mlkit_pose_detection: ^0.13.0
  permission_handler: ^11.3.1
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  firebase_messaging: ^15.0.0
  cloud_firestore: ^5.0.0
  cloud_functions: ^5.0.0
  shared_preferences: ^2.3.0
  flutter_secure_storage: ^9.2.2
  audioplayers: ^6.0.0
  pdf: ^3.11.0
  printing: ^5.13.4
  fl_chart: ^0.69.0
  image_picker: ^1.1.2
  sentry_flutter: ^8.9.0
  cached_network_image: ^3.3.1
  qr_flutter: ^4.1.0
  excel: ^4.0.6
  file_picker: ^8.1.4
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  image: ^4.2.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - logo.png
    - assets/images/
    - assets/videos/
    - assets/fonts/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo.ttf
