// Global app language (default: 'en')
String _appLanguage = 'en';

String getAppLanguage() => _appLanguage;
void setAppLanguage(String lang) => _appLanguage = lang;

class AppLocalizations {
  static const Map<String, String> _en = {
    'choose_language': 'Choose your language',
    'language_desc': 'Select the language you want to use in the app',
    'continue_btn': 'Continue',
    'back_btn': 'Back',
    'skip_btn': 'Skip',
    'next_btn': 'Next',
    'finish_btn': 'Finish',
    'get_started_btn': 'Get Started',
    'auth_sign_in': 'Sign In',
    'auth_sign_up': 'Sign Up',
    'auth_sign_in_action': 'Sign in',
    'auth_create_account': 'Create account',
    'auth_title_login': 'Welcome back',
    'auth_title_signup': 'Create your account',
    'auth_subtitle_login': 'Sign in to continue training',
    'auth_subtitle_signup': 'Start your AI football journey',
    'auth_password': 'Password',
    'auth_or_continue': 'or continue with',
    'auth_google': 'Continue with Google',
    'auth_google_soon': 'Google sign-in coming soon',
    'auth_terms': 'By continuing you agree to our Terms & Privacy Policy.',
    'error_invalid_email': 'Invalid email',
    'error_invalid_email_or_phone': 'Enter a valid email or phone number',
    'error_invalid_phone': 'Enter a valid phone number',
    'error_password_short': 'Password must be at least 6 characters',
    'error_name_required': 'Please enter your name',
    'error_connection': 'Connection error. Make sure the server is running.',
    'step_counter': 'Step {current} of {total}',
    'name_example': 'e.g. Ahmed',
    'role_adapt_hint': 'Drills will adapt to this role.',
    'pick_at_least_one': 'Pick at least 1',
    'selected_count': '{count} selected',
    'pro_label': 'Pro',
    'slide1_title': 'Joint angle analysis',
    'slide1_desc':
        'Real-time X-ray biomechanics tracks every bone angle - hip, knee and ankle - during your kicks.',
    'slide2_title': 'Shot power decoded',
    'slide2_desc':
        'AI maps your full skeleton to measure kick angle, pass accuracy and ball contact force instantly.',
    'slide3_title': 'Dribbling intelligence',
    'slide3_desc':
        'Track every touch through cone drills. Speed, agility and movement path - all measured live.',
    'profile_step1': 'About you',
    'profile_step2': 'Position',
    'profile_step3': 'Foot',
    'profile_step4': 'Focus areas',
    'profile_step1_desc': 'Tell us a bit about yourself.',
    'profile_step2_desc': 'Tap the spot where you usually play.',
    'profile_step3_desc': 'Which foot do you trust most?',
    'profile_step4_desc': 'Pick what you\'d like the AI to focus on.',
    'your_name': 'Your name',
    'age': 'Age',
    'left_foot': 'Left',
    'right_foot': 'Right',
    'both_feet': 'Both',
    'left_footed': 'Left-footed',
    'right_footed': 'Right-footed',
    'two_footed': 'Two-footed',
    'profile_ready': 'Profile ready!',
    'settings': 'Settings',
    'sound_effects': 'Sound Effects',
    'sound_on': 'Sound On',
    'sound_off': 'Sound Off',
    'achievements': 'Achievements',
    'sign_out': 'Sign out',
    'level': 'Level',
    'xp': 'XP',
    'coins': 'Coins',
    'streak': 'Streak',
    'app_language': 'App language',
    'language_settings_desc': 'Choose the language used across the Flutter app.',
    'account': 'Account',
    'player_name': 'Player name',
    'by_player': 'By {name}',
    'email': 'Email',
    'email_or_phone': 'Email or phone number',
    'phone_number': 'Phone number',
    'training_preferences': 'Training preferences',
    'training_preferences_desc':
        'Your profile choices personalize drills and analysis.',
    'edit_profile': 'Edit profile setup',
    'unlocked': 'Unlocked',
    'locked': 'Locked',
    'achievements_desc': 'Track your progress and training milestones.',
    'achievement_progress': '{done} of {total} unlocked',
    'achievement_profile_ready': 'Profile Ready',
    'achievement_profile_ready_desc':
        'Finish the player setup and build your profile.',
    'achievement_first_session': 'First Session',
    'achievement_first_session_desc': 'Complete your first AI training session.',
    'achievement_challenge_starter': 'Challenge Starter',
    'achievement_challenge_starter_desc': 'Complete one daily challenge.',
    'achievement_streak_builder': 'Streak Builder',
    'achievement_streak_builder_desc': 'Build a 3-day training streak.',
    'page_not_found': 'Page not found',
    'go_home': 'Go Home',
    'nav_home': 'Home',
    'nav_training': 'Training',
    'nav_stats': 'Stats',
    'nav_profile': 'Profile',
    'good_afternoon': 'Good afternoon,',
    'rank_beginner': 'Beginner',
    'rank_rookie': 'Rookie',
    'rank': 'Rank',
    'day_streak': 'Day streak',
    'daily_challenges': 'Daily Challenge',
    'done': 'done',
    'challenge_number': 'Challenge {index}',
    'challenge_subtitle': 'React and tap the lights as fast as you can.',
    'earn_reward': 'Earn {coins} coins and {xp} XP',
    'start_here': 'Start Here',
    'try_first_drill': 'Start Your First Drill',
    'first_drill_hint': 'Start with Hand Reaction - great for beginners!',
    'start_training': 'Start Training',
    'training_programs': 'Training Programs',
    'see_all': 'See all',
    'drill_count': '{count} drills',
    'search_training': 'Search for training',
    'no_drills_found': 'No drills found.',
    'category_all': 'All',
    'category_reaction': 'Reaction',
    'category_control': 'Control',
    'category_fitness': 'Fitness',
    'category_shooting': 'Shooting',
    'difficulty_beginner': 'Beginner',
    'difficulty_intermediate': 'Intermediate',
    'difficulty_advanced': 'Advanced',
    'drill_hand_reaction': 'Hand Reaction',
    'drill_foot_reaction': 'Foot Reaction',
    'drill_get_in_box': 'Get In The Box',
    'drill_rain_body': 'The Rain (Body)',
    'drill_rain_feet': 'The Rain (Feet)',
    'drill_ball_control': 'Close Control',
    'drill_first_touch': 'First Touch',
    'drill_sprint_cube': 'Sprint Cube',
    'drill_agility_grid': 'Agility Grid',
    'drill_power_shot': 'Power Shot',
    'drill_finisher': 'Finisher',
    'program_reaction_starter': 'Reaction Starter',
    'program_body_control': 'Body Control',
    'program_elite_finisher': 'Elite Finisher',
    'challenge_c1': 'Complete Hand Reaction 3 times',
    'challenge_c2': 'Score 80+ on Foot Reaction',
    'challenge_c3': 'Hold a perfect plank for 60s',
    'duration': 'Duration',
    'intensity': 'Intensity',
    'medium': 'Medium',
    'camera': 'Camera',
    'required': 'Required',
    'how_it_works': 'How it works',
    'how_it_works_body':
        'Position your phone so your full body is visible. Our AI tracks your movements, counts your reps, and scores every action in real time.',
    'assessment_hub_title': 'AI Physical Assessment',
    'assessment_hub_subtitle': 'Movement quality, balance and correction insights for every player.',
    'assessment_start': 'Start Assessment',
    'assessment_players_title': 'Player profiles',
    'assessment_no_players': 'No player profiles found yet.',
    'assessment_add_player': 'Add a player',
    'assessment_tips_title': 'Assessment guidance',
    'assessment_tips_body':
        'Use the camera view to capture a squat trial. Keep the full body visible and move slowly.',
    'assessment_select_title': 'Select player & test',
    'assessment_select_subtitle':
        'Choose a player and the assessment to begin.',
    'assessment_choose_test': 'Choose a test',
    'assessment_choose_player': 'Choose a player',
    'assessment_select_test_hint': 'Tap a test mode first, then select a player.',
    'assessment_test_short_squat': 'Squat form analysis',
    'assessment_test_short_singleLegBalance': 'Single-leg stability',
    'assessment_test_short_jumpLanding': 'Jump landing control',
    'assessment_test_short_lunge': 'Lunge alignment',
    'assessment_camera_title': 'Capture movement',
    'camera_permission_denied': 'Camera permission is required for assessments.',
    'camera_ready': 'Camera ready. Press start when you are in frame.',
    'camera_initialization_failed': 'Unable to initialize the camera.',
    'assessment_capturing': 'Capturing movement… keep steady.',
    'assessment_align_body': 'Align your full body in the frame.',
    'assessment_follow_instructions':
        'Keep your feet visible and perform a slow squat motion.',
    'assessment_start_capture': 'Start capture',
    'assessment_stop': 'Stop',
    'assessment_no_valid_frames':
        'No valid movement was captured. Try again with better visibility.',
    'assessment_processing': 'Processing assessment…',
    'assessment_result_title': 'Assessment result',
    'assessment_metric_breakdown': 'Angle metrics',
    'assessment_issues_title': 'Potential risk signals',
    'assessment_no_issues': 'No specific movement concerns were detected.',
    'assessment_no_tips': 'No additional tips at this time.',
    'assessment_drills_title': 'Recommended drills',
    'assessment_no_drills': 'No drill recommendations available.',
    'assessment_saved': 'Result saved',
    'assessment_save_result': 'Save result',
    'assessment_history_title': 'Assessment history',
    'assessment_history_empty': 'No past assessments for this player yet.',
    'assessment_feature_label': 'Movement assessment hub',
    'assessment_feature_subtitle':
        'Run a quick physical assessment and monitor movement quality over time.',
    'assessment_movement_quality': 'Movement quality',
    'assessment_symmetry': 'Asymmetry',
    'assessment_stability': 'Stability',
    'assessment_quality': 'Video quality',
    'player_name_label': 'Player name',
    'player_height_label': 'Height (cm)',
    'player_weight_label': 'Weight (kg)',
    'player_position_label': 'Position',
    'player_team_label': 'Team',
    'player_category_label': 'Category',
    'player_dominant_foot_label': 'Dominant foot',
    'player_injury_notes_label': 'Injury notes',
    'save_btn': 'Save',
    'player_name_required': 'Please enter a player name.',
    'place_player_here': 'Place player here',
    'subject_in_frame': 'Subject in frame',
    'camera_level': 'Camera level',
    'lighting': 'Lighting',
    'distance_3m': 'Distance ~3m',
    'recording_short': 'REC',
    'degrees_short': 'deg',
    'setup_quality': 'Setup quality',
    'excellent': 'Excellent',
    'adjust_setup': 'Adjust setup',
    'poor': 'Poor',
    'analyzing_performance': 'Analyzing your performance',
    'pipeline_subtitle': 'Our AI is reviewing your reps frame-by-frame',
    'pipeline_landmarks': 'Detecting body landmarks',
    'pipeline_tracking': 'Tracking movement & speed',
    'pipeline_biomechanics': 'Calculating biomechanics',
    'pipeline_scoring': 'Scoring your performance',
    'latest_analysis': 'Latest analysis',
    'score': 'Score',
    'top_speed': 'Top speed',
    'accuracy': 'Accuracy',
    'reps': 'Reps',
    'speed_over_time': 'Speed over time',
    'body_angles': 'Body angles (deg)',
    'fatigue_alert': 'Fatigue alert - Mild',
    'fatigue_body':
        'Your stride length dropped 12% in the last 3 reps. Consider a 60-second rest.',
    'virtual_coach': 'Virtual Coach',
    'coach_tip':
        'Great power on your strikes! Try delaying your support foot by ~10 cm to reduce rightward drift and improve accuracy.',
    'pick_next_drill': 'Pick the next drill',
    'angle_hip': 'Hip',
    'angle_knee': 'Knee',
    'angle_ankle': 'Ankle',
    'angle_spine': 'Spine',
    'camera_permission_title': 'Camera access needed',
    'camera_permission_body':
        'This drill uses your camera to track body movements in real time. No video is stored.',
    'allow_camera_btn': 'Allow Camera',
    'safety_warning_title': 'Safety first',
    'safety_warning_body':
        'Clear the area around you. Stop if you feel pain or dizziness. This app does not replace a coach.',
    'i_understand_btn': 'I understand',
    'demo_mode_notice': 'Demo mode — using simulated pose data',
    'status_warming_title': 'Starting up',
    'status_warming_hint': 'Warming up the camera...',
    'status_not_visible_title': 'Body not detected',
    'status_not_visible_hint': 'Step into the frame so your full body is visible.',
    'status_too_close_title': 'Too close',
    'status_too_close_hint': 'Step back until your full body fits in frame.',
    'status_low_light_title': 'Low light',
    'status_low_light_hint': 'Move to a brighter area or turn on more lights.',
    'status_ready_title': 'Ready to start',
    'status_ready_hint': 'Body detected. Press start when ready.',
    'chip_warming': 'Warming up',
    'chip_not_visible': 'Not visible',
    'chip_too_close': 'Too close',
    'chip_low_light': 'Low light',
    'chip_ready': 'Ready',
    'tip_full_body': 'Make sure your full body is visible from head to toe.',
    'tip_well_lit': 'Train in a well-lit room.',
    'tip_no_window': 'Avoid standing in front of a bright window.',
    'tip_step_back': 'Step back until your whole body fits in the frame.',
    'tip_2_3_meters': 'Keep 2–3 meters distance from the phone.',
    'tip_face_light': 'Face the light source instead of having it behind you.',
    'tip_turn_lights': 'Turn on more lights or open the curtains.',
    'body_detected': 'Body detected',
    'waiting_for_body': 'Waiting for body...',
    'start_exercise_btn': 'Start Exercise',
    'exit_training_btn': 'Exit',
    'instruction_label': 'Instructions',
    'instruction_box': 'Stand inside the box',
    'instruction_foot': 'React with your foot',
    'instruction_hand': 'React with your hand',
    'move_into_zone': 'Move into the zone',
    'tips_title': 'Tips',
    'timer_label': 'Time',
    'reps_label': 'Reps',
    'avg_label': 'Avg',
    'replay_btn': 'Replay',
    'exit_btn': 'Exit',
    'training_complete': 'Training complete!',
    'total_reps': 'Total reps',
    'avg_reaction': 'Avg reaction',
    'ob_path_title': 'Choose your training path',
    'ob_path_football': 'Football Only',
    'ob_path_fitness': 'Fitness Only',
    'ob_path_both': 'Football + Fitness',
    'ob_basic_title': 'About your body',
    'ob_height': 'Height (cm)',
    'ob_weight': 'Weight (kg)',
    'ob_gender': 'Gender',
    'ob_goals_title': 'Your Goals & Fitness',
    'ob_fitness_level': 'Fitness Level',
    'ob_goal': 'Main Goal',
    'ob_days_week': 'Days per week',
    'ob_duration': 'Session Duration (min)',
    'ob_injury': 'Injury Limitations',
    'ob_football_title': 'Football Details',
    'ob_skill_level': 'Skill Level',
    'ob_generating': 'Generating your AI Plan...',
    'monitoring_title': 'Wellness Monitoring',
    'monitoring_dashboard': 'Wellness Dashboard',
    'body_metrics': 'Body Metrics',
    'body_fat': 'Body Fat',
    'bmi': 'BMI',
    'save_metrics': 'Save Metrics',
    'hooper_index': 'Hooper Index',
    'pre_training': 'Pre-Training Wellness',
    'post_training': 'Post-Training RPE',
    'sleep_quality': 'Sleep Quality',
    'muscle_soreness': 'Muscle Soreness',
    'hooper_score': 'Hooper Score',
    'rpe': 'Rate Perceived Exertion',
    'rpe_score': 'RPE Score',
    'training_load': 'Training Load',
    'duration_minutes': 'Duration (minutes)',
    'session_type': 'Session Type',
    'readiness_score': 'Readiness Score',
    'wellness_status': 'Wellness Status',
    'high_risk': 'High Risk',
    'ready_to_go': 'Ready to go',
    'monitor_closely': 'Monitor closely',
    'alerts': 'Alerts',
    'insights': 'AI Insights',
    'recommendations': 'Recommendations',
    'weekly_load': 'Weekly Load',
    'acwr': 'Load Ratio (ACWR)',
    'acute_load': 'Acute Load',
    'chronic_load': 'Chronic Load',
    'injury_risk': 'Injury Risk',
    'team_wellness': 'Team Wellness',
    'team_readiness': 'Team Readiness',
    'players_at_risk': 'Players at Injury Risk',
    'average_rpe': 'Average RPE',
    'recovery_score': 'Recovery Score',
    'checked_in_today': 'Checked In Today',
    'players_needing_attention': 'Players Needing Attention',
    'submit_checkin': 'Submit Check-In',
    'log_session': 'Log Session',
    'no_data_yet': 'No data yet',
    'sleep_hours': 'Sleep Hours',
    'latest_record': 'Latest Record',
    'recovery_session': 'Recovery session',
    'mobility': 'Mobility work',
    'light_stretching': 'Light stretching',
    'reduced_intensity': 'Reduced intensity',
    'extra_recovery': 'Extra recovery time',
    'prioritize_sleep': 'Prioritize sleep',
    'summary': 'Summary',
    'total_checked_in': 'Total Checked In',
  };

  static const Map<String, String> _ar = {
    'choose_language': 'اختر لغتك',
    'language_desc': 'حدد اللغة التي تريد استخدامها في التطبيق',
    'continue_btn': 'متابعة',
    'back_btn': 'رجوع',
    'skip_btn': 'تخطي',
    'next_btn': 'التالي',
    'finish_btn': 'إنهاء',
    'get_started_btn': 'ابدأ الآن',
    'auth_sign_in': 'تسجيل الدخول',
    'auth_sign_up': 'إنشاء حساب',
    'auth_sign_in_action': 'دخول',
    'auth_create_account': 'إنشاء الحساب',
    'auth_title_login': 'مرحباً بعودتك',
    'auth_title_signup': 'أنشئ حسابك',
    'auth_subtitle_login': 'سجل دخولك لمواصلة التدريب',
    'auth_subtitle_signup': 'ابدأ رحلتك الكروية مع الذكاء الاصطناعي',
    'auth_password': 'كلمة المرور',
    'auth_or_continue': 'أو تابع باستخدام',
    'auth_google': 'المتابعة عبر Google',
    'auth_google_soon': 'تسجيل Google قادم قريباً',
    'auth_terms': 'بالمتابعة أنت توافق على الشروط وسياسة الخصوصية.',
    'error_invalid_email': 'البريد الإلكتروني غير صحيح',
    'error_invalid_email_or_phone': 'أدخل بريد إلكتروني أو رقم هاتف صحيح',
    'error_invalid_phone': 'أدخل رقم هاتف صحيح',
    'error_password_short': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
    'error_name_required': 'أدخل اسمك',
    'error_connection': 'تعذر الاتصال. تأكد أن الخادم يعمل.',
    'step_counter': 'الخطوة {current} من {total}',
    'name_example': 'مثال: أحمد',
    'role_adapt_hint': 'سيتم تخصيص التمارين حسب هذا المركز.',
    'pick_at_least_one': 'اختر واحداً على الأقل',
    'selected_count': '{count} محدد',
    'pro_label': 'محترف',
    'slide1_title': 'تحليل زوايا المفاصل',
    'slide1_desc':
        'تحليل حركي مباشر يتتبع زاوية الورك والركبة والكاحل أثناء التسديد.',
    'slide2_title': 'فهم قوة التسديد',
    'slide2_desc':
        'يرسم الذكاء الاصطناعي الهيكل الكامل لقياس زاوية التسديد ودقة التمرير وقوة لمس الكرة فوراً.',
    'slide3_title': 'ذكاء المراوغة',
    'slide3_desc':
        'تتبع كل لمسة عبر تدريبات الأقماع مع قياس السرعة والرشاقة ومسار الحركة مباشرة.',
    'profile_step1': 'عن نفسك',
    'profile_step2': 'المركز',
    'profile_step3': 'القدم',
    'profile_step4': 'نقاط التركيز',
    'profile_step1_desc': 'أخبرنا قليلاً عن نفسك.',
    'profile_step2_desc': 'اضغط على المكان الذي تلعب فيه عادة.',
    'profile_step3_desc': 'أي قدم تثق بها أكثر؟',
    'profile_step4_desc': 'اختر ما تريد من الذكاء الاصطناعي التركيز عليه.',
    'your_name': 'اسمك',
    'age': 'العمر',
    'left_foot': 'اليسار',
    'right_foot': 'اليمين',
    'both_feet': 'كلاهما',
    'left_footed': 'أيسر القدم',
    'right_footed': 'أيمن القدم',
    'two_footed': 'يجيد القدمين',
    'profile_ready': 'ملفك جاهز!',
    'settings': 'الإعدادات',
    'sound_effects': 'المؤثرات الصوتية',
    'sound_on': 'الصوت مفعّل',
    'sound_off': 'الصوت مطفأ',
    'achievements': 'الإنجازات',
    'sign_out': 'تسجيل الخروج',
    'level': 'المستوى',
    'coins': 'العملات',
    'streak': 'السلسلة',
    'app_language': 'لغة التطبيق',
    'language_settings_desc': 'اختر اللغة المستخدمة داخل التطبيق.',
    'account': 'الحساب',
    'player_name': 'اسم اللاعب',
    'by_player': 'بواسطة {name}',
    'email': 'البريد الإلكتروني',
    'email_or_phone': 'البريد الإلكتروني أو رقم الهاتف',
    'phone_number': 'رقم الهاتف',
    'training_preferences': 'تفضيلات التدريب',
    'training_preferences_desc': 'اختيارات ملفك تخصص التمارين والتحليل.',
    'edit_profile': 'تعديل الملف',
    'unlocked': 'مفتوح',
    'locked': 'مغلق',
    'achievements_desc': 'تابع تقدمك وإنجازاتك التدريبية.',
    'achievement_progress': '{done} من {total} مفتوحة',
    'achievement_profile_ready': 'الملف جاهز',
    'achievement_profile_ready_desc': 'أكمل إعداد اللاعب وأنشئ ملفك.',
    'achievement_first_session': 'أول حصة',
    'achievement_first_session_desc': 'أكمل أول جلسة تدريب بالذكاء الاصطناعي.',
    'achievement_challenge_starter': 'بداية التحديات',
    'achievement_challenge_starter_desc': 'أكمل تحدياً يومياً واحداً.',
    'achievement_streak_builder': 'بناء السلسلة',
    'achievement_streak_builder_desc': 'كوّن سلسلة تدريب لمدة 3 أيام.',
    'page_not_found': 'الصفحة غير موجودة',
    'go_home': 'العودة للرئيسية',
    'nav_home': 'الرئيسية',
    'nav_training': 'التدريب',
    'nav_stats': 'الإحصائيات',
    'nav_profile': 'الملف',
    'good_afternoon': 'مساء الخير،',
    'rank_beginner': 'مبتدئ',
    'rank_rookie': 'ناشئ',
    'rank': 'الرتبة',
    'day_streak': 'سلسلة الأيام',
    'daily_challenges': 'تحديات اليوم',
    'done': 'مكتمل',
    'challenge_number': 'تحدي {index}',
    'challenge_subtitle': 'تفاعل واضغط على الأضواء بأسرع ما تستطيع.',
    'earn_reward': 'اكسب {coins} عملة و {xp} خبرة',
    'start_here': 'ابدأ هنا',
    'try_first_drill': 'جرب أول تمرين',
    'first_drill_hint': 'ابدأ برد فعل اليد، مناسب جداً للمبتدئين!',
    'start_training': 'ابدأ التدريب',
    'training_programs': 'برامج التدريب',
    'see_all': 'عرض الكل',
    'drill_count': '{count} تمارين',
    'search_training': 'ابحث عن تدريب',
    'no_drills_found': 'لا توجد تمارين.',
    'category_all': 'الكل',
    'category_reaction': 'رد الفعل',
    'category_control': 'التحكم',
    'category_fitness': 'اللياقة',
    'category_shooting': 'التسديد',
    'difficulty_beginner': 'مبتدئ',
    'difficulty_intermediate': 'متوسط',
    'difficulty_advanced': 'متقدم',
    'duration': 'المدة',
    'intensity': 'الشدة',
    'medium': 'متوسطة',
    'camera': 'الكاميرا',
    'required': 'مطلوبة',
    'how_it_works': 'طريقة العمل',
    'how_it_works_body':
        'ضع الهاتف بحيث يظهر جسمك بالكامل. يتتبع الذكاء الاصطناعي حركتك ويحسب التكرارات ويقيّم كل حركة مباشرة.',
    'start_drill': 'بدء التمرين',
    'place_player_here': 'ضع اللاعب هنا',
    'subject_in_frame': 'اللاعب داخل الإطار',
    'camera_level': 'الكاميرا مستوية',
    'lighting': 'الإضاءة',
    'distance_3m': 'المسافة حوالي 3م',
    'recording_short': 'تسجيل',
    'degrees_short': 'درجة',
    'setup_quality': 'جودة الإعداد',
    'excellent': 'ممتاز',
    'adjust_setup': 'اضبط الإعداد',
    'poor': 'ضعيف',
    'analyzing_performance': 'جاري تحليل أدائك',
    'pipeline_subtitle': 'الذكاء الاصطناعي يراجع التكرارات إطاراً بإطار',
    'pipeline_landmarks': 'تحديد نقاط الجسم',
    'pipeline_tracking': 'تتبع الحركة والسرعة',
    'pipeline_biomechanics': 'حساب ميكانيكا الجسم',
    'pipeline_scoring': 'تقييم الأداء',
    'latest_analysis': 'آخر تحليل',
    'score': 'النتيجة',
    'top_speed': 'أعلى سرعة',
    'accuracy': 'الدقة',
    'reps': 'التكرارات',
    'speed_over_time': 'السرعة عبر الزمن',
    'body_angles': 'زوايا الجسم (درجة)',
    'fatigue_alert': 'تنبيه إجهاد - خفيف',
    'fatigue_body':
        'انخفض طول خطوتك 12% في آخر 3 تكرارات. خذ راحة لمدة 60 ثانية.',
    'virtual_coach': 'المدرب الافتراضي',
    'coach_tip':
        'قوة التسديد ممتازة! جرّب تأخير قدم الارتكاز حوالي 10 سم لتحسين الدقة.',
    'pick_next_drill': 'اختر التمرين التالي',
    'angle_hip': 'الورك',
    'angle_knee': 'الركبة',
    'angle_ankle': 'الكاحل',
    'angle_spine': 'الظهر',
    'camera_permission_title': 'مطلوب الوصول للكاميرا',
    'camera_permission_body':
        'يستخدم هذا التمرين كاميرتك لتتبع حركات الجسم في الوقت الفعلي. لا يتم حفظ أي فيديو.',
    'allow_camera_btn': 'السماح للكاميرا',
    'safety_warning_title': 'السلامة أولاً',
    'safety_warning_body':
        'أفرغ المنطقة من حولك. توقف إذا شعرت بألم أو دوار. هذا التطبيق لا يغني عن المدرب.',
    'i_understand_btn': 'فهمت',
    'demo_mode_notice': 'وضع تجريبي — بيانات وضعية محاكاة',
    'status_warming_title': 'جارٍ التشغيل',
    'status_warming_hint': 'تهيئة الكاميرا...',
    'status_not_visible_title': 'الجسم غير مكتشف',
    'status_not_visible_hint': 'ادخل إلى الإطار حتى يظهر جسمك بالكامل.',
    'status_too_close_title': 'قريب جداً',
    'status_too_close_hint': 'ابتعد حتى يظهر جسمك كاملاً في الإطار.',
    'status_low_light_title': 'إضاءة ضعيفة',
    'status_low_light_hint': 'انتقل إلى مكان أكثر إضاءة أو أضئ المزيد من الأنوار.',
    'status_ready_title': 'جاهز للبدء',
    'status_ready_hint': 'تم اكتشاف الجسم. اضغط ابدأ عندما تكون مستعداً.',
    'chip_warming': 'جارٍ التهيئة',
    'chip_not_visible': 'غير مرئي',
    'chip_too_close': 'قريب جداً',
    'chip_low_light': 'إضاءة ضعيفة',
    'chip_ready': 'جاهز',
    'tip_full_body': 'تأكد أن جسمك يظهر كاملاً من الرأس حتى القدم.',
    'tip_well_lit': 'تدرب في غرفة جيدة الإضاءة.',
    'tip_no_window': 'تجنب الوقوف أمام نافذة مضاءة.',
    'tip_step_back': 'ابتعد حتى يظهر جسمك كاملاً في الإطار.',
    'tip_2_3_meters': 'حافظ على مسافة 2–3 أمتار من الهاتف.',
    'tip_face_light': 'اتجه نحو مصدر الضوء بدلاً من أن يكون خلفك.',
    'tip_turn_lights': 'أضئ المزيد من الأنوار أو افتح الستائر.',
    'body_detected': 'تم اكتشاف الجسم',
    'waiting_for_body': 'في انتظار الجسم...',
    'start_exercise_btn': 'بدء التمرين',
    'exit_training_btn': 'خروج',
    'instruction_label': 'التعليمات',
    'instruction_box': 'قف داخل المنطقة',
    'instruction_foot': 'تفاعل بقدمك',
    'instruction_hand': 'تفاعل بيدك',
    'move_into_zone': 'ادخل إلى المنطقة',
    'tips_title': 'نصائح',
    'timer_label': 'الوقت',
    'reps_label': 'التكرارات',
    'avg_label': 'المتوسط',
    'replay_btn': 'إعادة',
    'exit_btn': 'خروج',
    'training_complete': 'انتهى التدريب!',
    'total_reps': 'إجمالي التكرارات',
    'avg_reaction': 'متوسط رد الفعل',
    'ob_path_title': 'اختر مسار التدريب الخاص بك',
    'ob_path_football': 'كرة قدم فقط',
    'ob_path_fitness': 'لياقة بدنية فقط',
    'ob_path_both': 'كرة قدم + لياقة',
    'ob_basic_title': 'بيانات الجسم',
    'ob_height': 'الطول (سم)',
    'ob_weight': 'الوزن (كجم)',
    'ob_gender': 'الجنس',
    'ob_goals_title': 'أهدافك ومستوى لياقتك',
    'ob_fitness_level': 'مستوى اللياقة',
    'ob_goal': 'الهدف الرئيسي',
    'ob_days_week': 'أيام التدريب في الأسبوع',
    'ob_duration': 'مدة الحصة (دقائق)',
    'ob_injury': 'الإصابات أو القيود',
    'ob_football_title': 'تفاصيل كرة القدم',
    'ob_skill_level': 'مستوى المهارة',
    'ob_generating': 'جاري إنشاء خطة الذكاء الاصطناعي...',
    'monitoring_title': 'مراقبة الجاهزية',
    'monitoring_dashboard': 'لوحة الجاهزية',
    'body_metrics': 'القياسات الجسدية',
    'body_fat': 'نسبة الدهون',
    'bmi': 'مؤشر كتلة الجسم',
    'save_metrics': 'حفظ القياسات',
    'hooper_index': 'مؤشر هوبر',
    'pre_training': 'الجاهزية قبل التمرين',
    'post_training': 'تقييم الإرهاق بعد التمرين',
    'sleep_quality': 'جودة النوم',
    'muscle_soreness': 'تعب العضلات',
    'hooper_score': 'درجة هوبر',
    'rpe': 'تقييم الإرهاق المدرك',
    'rpe_score': 'درجة الإرهاق',
    'training_load': 'حمل التدريب',
    'duration_minutes': 'المدة (دقائق)',
    'session_type': 'نوع الحصة',
    'readiness_score': 'درجة الجاهزية',
    'wellness_status': 'حالة الجاهزية',
    'high_risk': 'خطر مرتفع',
    'ready_to_go': 'جاهز للتدريب',
    'monitor_closely': 'مراقبة دقيقة مطلوبة',
    'alerts': 'التنبيهات',
    'insights': 'التحليلات الذكية',
    'recommendations': 'التوصيات',
    'weekly_load': 'حمل الأسبوع',
    'acwr': 'نسبة الحمل',
    'acute_load': 'الحمل الحاد',
    'chronic_load': 'الحمل المزمن',
    'injury_risk': 'خطر الإصابة',
    'team_wellness': 'جاهزية الفريق',
    'team_readiness': 'جاهزية الفريق',
    'players_at_risk': 'لاعبون في خطر',
    'average_rpe': 'متوسط الإرهاق',
    'recovery_score': 'درجة التعافي',
    'checked_in_today': 'المسجلون اليوم',
    'players_needing_attention': 'لاعبون يحتاجون متابعة',
    'submit_checkin': 'تسجيل الحالة',
    'log_session': 'تسجيل الحصة',
    'no_data_yet': 'لا توجد بيانات بعد',
    'sleep_hours': 'ساعات النوم',
    'latest_record': 'آخر قياس',
    'recovery_session': 'حصة استشفاء',
    'mobility': 'تحريك المفاصل',
    'light_stretching': 'استطالة خفيفة',
    'reduced_intensity': 'تقليل الشدة',
    'extra_recovery': 'وقت استشفاء إضافي',
    'prioritize_sleep': 'أعط النوم أولوية',
    'summary': 'الملخص',
    'total_checked_in': 'إجمالي المسجلين',
  };

  static const Map<String, String> _fr = {
    'choose_language': 'Choisir votre langue',
    'language_desc': 'Selectionnez la langue a utiliser dans l\'application',
    'continue_btn': 'Continuer',
    'back_btn': 'Retour',
    'skip_btn': 'Passer',
    'next_btn': 'Suivant',
    'finish_btn': 'Terminer',
    'get_started_btn': 'Commencer',
    'auth_sign_in': 'Connexion',
    'auth_sign_up': 'Inscription',
    'auth_sign_in_action': 'Se connecter',
    'auth_create_account': 'Creer un compte',
    'auth_title_login': 'Bon retour',
    'auth_title_signup': 'Creez votre compte',
    'auth_subtitle_login': 'Connectez-vous pour continuer l\'entrainement',
    'auth_subtitle_signup': 'Commencez votre parcours football avec l\'IA',
    'auth_password': 'Mot de passe',
    'auth_or_continue': 'ou continuer avec',
    'auth_google': 'Continuer avec Google',
    'auth_google_soon': 'Connexion Google bientot disponible',
    'auth_terms':
        'En continuant, vous acceptez les conditions et la politique de confidentialite.',
    'error_invalid_email': 'Email invalide',
    'error_invalid_email_or_phone': 'Saisissez un email ou un numero valide',
    'error_invalid_phone': 'Saisissez un numero de telephone valide',
    'error_password_short': 'Le mot de passe doit contenir au moins 6 caracteres',
    'error_name_required': 'Veuillez saisir votre nom',
    'error_connection': 'Erreur de connexion. Verifiez que le serveur fonctionne.',
    'step_counter': 'Etape {current} sur {total}',
    'name_example': 'ex. Ahmed',
    'role_adapt_hint': 'Les exercices s\'adapteront a ce role.',
    'pick_at_least_one': 'Choisissez au moins 1',
    'selected_count': '{count} selectionne(s)',
    'pro_label': 'Pro',
    'slide1_title': 'Analyse des angles articulaires',
    'slide1_desc':
        'La biomecanique en temps reel suit la hanche, le genou et la cheville pendant vos tirs.',
    'slide2_title': 'Puissance de tir decodee',
    'slide2_desc':
        'L\'IA mesure l\'angle de tir, la precision de passe et la force de contact instantanement.',
    'slide3_title': 'Intelligence de dribble',
    'slide3_desc':
        'Suivez chaque touche dans les exercices de cones avec vitesse, agilite et trajectoire.',
    'profile_step1': 'A propos de vous',
    'profile_step2': 'Poste',
    'profile_step3': 'Pied',
    'profile_step4': 'Axes de travail',
    'profile_step1_desc': 'Parlez-nous un peu de vous.',
    'profile_step2_desc': 'Touchez la zone ou vous jouez habituellement.',
    'profile_step3_desc': 'Quel pied utilisez-vous le plus?',
    'profile_step4_desc': 'Choisissez ce que l\'IA doit travailler.',
    'your_name': 'Votre nom',
    'age': 'Age',
    'left_foot': 'Gauche',
    'right_foot': 'Droite',
    'both_feet': 'Les deux',
    'left_footed': 'Pied gauche',
    'right_footed': 'Pied droit',
    'two_footed': 'Deux pieds',
    'settings': 'Parametres',
    'achievements': 'Reussites',
    'sign_out': 'Deconnexion',
    'app_language': 'Langue de l\'application',
    'language_settings_desc': 'Choisissez la langue utilisee dans l\'application.',
    'account': 'Compte',
    'player_name': 'Nom du joueur',
    'email': 'Email',
    'email_or_phone': 'Email ou telephone',
    'phone_number': 'Telephone',
    'training_preferences': 'Preferences d\'entrainement',
    'training_preferences_desc':
        'Vos choix de profil personnalisent les exercices et l\'analyse.',
    'edit_profile': 'Modifier le profil',
    'nav_home': 'Accueil',
    'nav_training': 'Entrainement',
    'nav_stats': 'Stats',
    'nav_profile': 'Profil',
    'good_afternoon': 'Bonjour,',
    'daily_challenges': 'Defis du jour',
    'challenge_subtitle': 'Reagissez et touchez les lumieres le plus vite possible.',
    'training_programs': 'Programmes',
    'search_training': 'Rechercher un entrainement',
    'no_drills_found': 'Aucun exercice trouve.',
    'duration': 'Duree',
    'intensity': 'Intensite',
    'camera': 'Camera',
    'required': 'Requise',
    'how_it_works': 'Comment ca marche',
    'start_drill': 'Demarrer l\'exercice',
    'analyzing_performance': 'Analyse de votre performance',
    'latest_analysis': 'Derniere analyse',
    'top_speed': 'Vitesse max',
    'accuracy': 'Precision',
    'reps': 'Repetitions',
    'virtual_coach': 'Coach virtuel',
    'start_training': 'Demarrer',
    'ob_path_title': 'Choisissez votre parcours',
    'ob_path_football': 'Football uniquement',
    'ob_path_fitness': 'Fitness uniquement',
    'ob_path_both': 'Football + Fitness',
    'ob_basic_title': 'A propos de votre corps',
    'ob_height': 'Taille (cm)',
    'ob_weight': 'Poids (kg)',
    'ob_gender': 'Genre',
    'ob_goals_title': 'Vos objectifs',
    'ob_fitness_level': 'Niveau de fitness',
    'ob_goal': 'Objectif principal',
    'ob_days_week': 'Jours par semaine',
    'ob_duration': 'Duree de session (min)',
    'ob_injury': 'Blessures ou limitations',
    'ob_football_title': 'Details Football',
    'ob_skill_level': 'Niveau de competence',
    'ob_generating': 'Generation de votre plan IA...',
  };

  static Map<String, String> _activeMap() {
    switch (getAppLanguage()) {
      case 'ar':
        return _ar;
      case 'fr':
        return _fr;
      default:
        return _en;
    }
  }

  static String get(String key) {
    return _activeMap()[key] ?? _en[key] ?? key;
  }

  static String format(String key, Map<String, Object> values) {
    var text = get(key);
    for (final entry in values.entries) {
      text = text.replaceAll('{${entry.key}}', entry.value.toString());
    }
    return text;
  }
}
