// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTh6RZqu6bcml_cBRtUAJJUsIBIWVx0Uk',
    appId: '1:947466090687:web:c30607069f649da68cee0a',
    messagingSenderId: '947466090687',
    projectId: 'al-merrikh',
    authDomain: 'al-merrikh.firebaseapp.com',
    storageBucket: 'al-merrikh.firebasestorage.app',
    measurementId: 'G-2XYDG8PX26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU1RaaMTWIap-pS2moYHwaFUnaYttZNmA',
    appId: '1:947466090687:android:efd24498843f01568cee0a',
    messagingSenderId: '947466090687',
    projectId: 'al-merrikh',
    storageBucket: 'al-merrikh.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH7PIgS9rbawwkDnN1Xca8N6Jv_bB-8lw',
    appId: '1:947466090687:ios:4037bacc450782e58cee0a',
    messagingSenderId: '947466090687',
    projectId: 'al-merrikh',
    storageBucket: 'al-merrikh.firebasestorage.app',
    iosBundleId: 'com.nextkick.almerrikh',
  );
}
